server:
    port: 8761
    
spring:
    application:
        name: apieureka

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        